global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "rules/alerts.yml"
  - "rules/recording.yml"

scrape_configs:
  # Base system metrics
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  # Database exporter metrics
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse-exporter:9116"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  # Grafana
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  # NearYou services
  - job_name: "nearyou_dashboard"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets:
          - "dashboard-user:8003"
        labels:
          service: "dashboard-user"
  
  - job_name: "nearyou_message_generator"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets:
          - "message-generator:8001"
        labels:
          service: "message-generator"
  
  # Pushgateway per metriche batch
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]